# GitHub action
# https://github.com/marketplace/actions/save-to-software-heritage

name: Achive ğŸ—ƒï¸ repository to Software Heritage

on:
  release:
    types: [created]

jobs:
  swh-archive:
    runs-on: ubuntu-latest
    steps:
    - name: Save repository to Software Heritage
      uses: sdruskat/swh-save-action@v1.0.1

